name: Deploy to Render

on:
  push:
    branches:
      - main  # lub 'master' – zależnie od nazwy głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
