name: Deploy to Render

on:
  push:
    branches:
      - render-autodeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-d11mqfogjchc73864fqg?key=0qGiQwhXpew
