name: Deploy to Render

on:
  push:
    branches:
      - main
      - render-autodeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production



    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
